version: 2
jobs:
  run-tests:
    working_directory: ~/double_click
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt upgrade
      - run: sudo apt install python3.7
      - run: sudo pip install tox
      - run: tox
  build-deploy:
    working_directory: ~/double_click
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run: rm -fr dist/
      - run: python setup.py sdist
      - run: python setup.py bdist_wheel
      - run: pip install twine
      - run: twine upload --username $USERNAME --password $PASSWORD dist/*
workflows:
  version: 2
  build_and_test:
    jobs:
      - run-tests
      - build-deploy:
          context: pypi
          requires:
            - run-tests
          filters:
            branches:
              only: master
