version: 2
jobs:
  run_tests:
    working_directory: ~/double_click
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt upgrade
      - run: sudo apt install python3.7
      - run: sudo pip install -r requirements.txt
      - run: tox
workflows:
  version: 2
  build_and_test:
    jobs:
      - run_tests
