version: 2
jobs:
  run_tests:
    working_directory: ~/double_click
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run: tox
workflows:
  version: 2
  build_and_test:
    jobs:
      - run_pytest
