version: 2
jobs:
  build:
    working_directory: ~/double_click
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run: ls -R
      - run: sudo pip install -r requirements.txt
      - run: python -m pytest